### ISSUE TITLE
Static builds (still) broken

### ISSUE THREAD

**Issue by jeroen** [silnrsi/graphite#33]
A while ago I send a pr to [enable shared and static builds](https://github.com/silnrsi/graphite/pull/12). This was rejected in favor of an alternative solution. 

I now tried with the latest release but building with `-DBUILD_SHARED_LIBS=OFF` still doesn't work:
```
==> cmake . -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release
Last 15 lines from /Users/jeroen/Library/Logs/Homebrew/graphite2/01.cmake:
-- Check size of size_t
-- Check size of size_t - done
-- Configuring done
CMake Error at Graphite.cmake:6 (add_test):
  Error evaluating generator expression:

    $<TARGET_SONAME_FILE:graphite2>

  TARGET_SONAME_FILE is allowed only for SHARED libraries.
Call Stack (most recent call first):
  src/CMakeLists.txt:152 (nolib_test)
```

**Comment by tim-eves** [comment]
I think must be some difference in the build environment or perhaps version of cmake (I'm on 3.9, but I believe this should work on 3.0) as this works fine on my developer machine (linux).  BTW you shouldn't need to pass `-DNDEBUG` when building any of the release types (`Release`, `RelMinSize` or `RelWithDebInfo`) as that is already set by cmake by defautl, if you do need to, then that might suggest that your cmake build options aren't getting passed to cmake correctly. Could you check new the begining of the cmake output from a clean build directory and check if it output 'Building library: static'.  Also is this a clean cmake run?  Typically cmake is run in subdir build directory not the toplevel source dir and the only way to clean CMake generated files is to remove it's build dir (or it's contents).  One last thing to check is are you using the latest master banch, since the branch I mentioned in the pr discusion has long since been merged into master?

Here is my cmake output: 
```
cmake .. -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release
-- Found PythonInterp: /usr/bin/python (found version "2.7.14") 
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build: Release
-- Building library: static
-- File Face support: enabled
-- Tracing support: enabled
-- Using vm machine type: direct
-- Compiler ID is: GNU
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tim/workspace/graphitedev/master/build-static
```
Here's the section of `src/CMakeLists.txt` that should be preventing the problem you're having:
Line 129:
```
        if (BUILD_SHARED_LIBS)
            nolib_test(stdc++ $<TARGET_SONAME_FILE:graphite2>)
        endif (BUILD_SHARED_LIBS)
```
The error message you're getting suggests that BUILD_SHARED_LIBS isn't being set despite your command line doing exactly that.

**Comment by jeroen** [comment]
I see the problem now. I am on MacOS and currently the `BUILD_SHARED_LIBS` is defined only for Linux. Can you do the same inside the `if  (${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")` block?

**Comment by spl** [comment]
I ran into this, too. I believe #54 should fix it.
