### ISSUE TITLE
graphite2::LANG_ENTRIES should go in a read-only data section

### ISSUE THREAD

**Issue by rvandermeulen** [silnrsi/graphite#9]
Reported in Mozilla's bug tracker ([bug 1334300](https://bugzilla.mozilla.org/show_bug.cgi?id=1334300)):
Marking LANG_ENTRIES as constexpr ensures that it goes into a read-only section, and trims 44k from xul.dll, mostly by removing unnecessary dynamic initializers.

Sample patch:
https://bugzilla.mozilla.org/attachment.cgi?id=8836447&action=diff

**Comment by mhosken** [comment]
The request is to remove the const from within the IsoLangEntry definition due to this bug in Visual Studio: https://bugzilla.mozilla.org/show_bug.cgi?id=1334254

Such a change feels temporary to me, given that I assume MS will fix this in due course. OTOH it doesn't cause problems to remove the consts, and the only use of the structure is a const itself.

**Comment by tim-eves** [comment]
This bug appears to have been fixed by commit f7bbdd87d510d587c872e314d6458160c0069c65
